spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
  #Redis配置
  redis:
    database: 0
    host: 192.168.245.128
    # Redis服务器连接端口
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8      # 连接池中的最大空闲连接
        min-idle: 0      # 连接池中的最小空闲连接
    timeout: 300         # 连接超时时间（毫秒）

####日志配置
logging:
  level:
    root: info
    com.cxzjava.blog: debug
  file:
    name: log/blog-dev.log
mybatis:
  mapper-locations: classpath:mapper/*.xml  #ָ指定myBatis的核心配置文件与Mapper映射文件
  type-aliases-package: com.cxzjava.blog.pojo   #定义别名

